# Generated by Django 3.0 on 2020-03-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20200316_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='user',
            new_name='user1',
        ),
    ]
