# Generated by Django 3.0 on 2020-03-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20200315_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='nome',
        ),
    ]
