# Generated by Django 3.0 on 2020-03-31 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20200321_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peop', to='pets.People'),
        ),
    ]
