# Generated by Django 3.0 on 2020-04-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20200331_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'CACHORRO'), (2, 'GATO'), (3, 'ANDORINHA'), (4, 'PAPAGAIO'), (5, 'IGUANA'), (6, 'CAVALO'), (7, 'ORNITORRINCO'), (8, 'LHAMA')]),
        ),
    ]
